name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GITHUB_ACTOR }} --password-stdin

    - name: Build and Push Docker image
      run: |
        docker buildx build --platform linux/amd64 --tag ghcr.io/${{ secrets.GITHUB_ACTOR }}/js-docker-test-example:latest --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH into GCP VM and deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.GCP_VM_IP }}
        username: ${{ secrets.GCP_VM_USERNAME }}
        key: ${{ secrets.GCP_VM_SSH_KEY }}
        script: |
          docker pull ghcr.io/${{ secrets.GITHUB_ACTOR }}/js-docker-test-example:latest
          docker stop $(docker ps -q --filter ancestor=ghcr.io/${{ secrets.GITHUB_ACTOR }}/js-docker-test-example:latest)
          docker rm $(docker ps -a -q --filter ancestor=ghcr.io/${{ secrets.GITHUB_ACTOR }}/js-docker-test-example:latest)
          docker run -d -p 80:80 -p 443:443 -p 5001:5001 ghcr.io/${{ secrets.GITHUB_ACTOR }}/js-docker-test-example:latest
