name: publish

on:
  push:
    branches:
      - main

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: haydensookchand
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build the Docker image
        run: docker build . -t ghcr.io/haydensookchand/js-docker-image:latest

      - name: Push the Docker image to GitHub Container Registry
        run: docker push ghcr.io/haydensookchand/js-docker-image:latest

      - name: Stop and remove any existing containers using port 5001
        run: |
          docker ps --filter "publish=5001" -q | xargs -r docker stop
          docker ps -a --filter "publish=5001" -q | xargs -r docker rm

      - name: Deploy to GCP VM.
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GCP_VM_SSH_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > id_rsa
          chmod 600 id_rsa
          ssh -o StrictHostKeyChecking=no -i id_rsa haydensookchand@104.154.114.249 "docker login ghcr.io -u haydensookchand -p ${{ secrets.GHCR_TOKEN }} && docker pull ghcr.io/haydensookchand/js-docker-image:latest && docker run -d -p 80:80 -p 443:443 -p 5001:5001 ghcr.io/haydensookchand/js-docker-image:latest"
