name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      env:
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      run: echo "${{ env.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/${{ github.actor }}/my-image-name:$(date +%s)

    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.actor }}/my-image-name:$(date +%s)
